### ISSUE TITLE
copas.step() throws error

### ISSUE THREAD

**Issue by okroth** [keplerproject/copas#21]
According to its documentation in the reference manual, copas.step() should return nil plus error message in case of errors. However, if _select(), which is called by step(), returns anything (else than "timeout") copas.step() calls error() which stops the whle program, as it is difficult to catch this one.
Is this intentional? 
Note: errors in the threads itself are handled.

**Comment by Tieske** [comment]
fixed in #25 throwing an error was not correct. Docs tell that `step` returns nil + error.
