### ISSUE TITLE
add lua 5.3 (tests pass already)

### ISSUE THREAD

**Issue by LennyPenny** [keplerproject/copas#27]
I ran all the tests on lua 5.3 and they seem to work fine

**Comment by Tieske** [comment]
well that's great. But what is your suggestion we do with that?

**Comment by hishamhm** [comment]
I think he means that the rockspec is marked as "< 5.3"

**Comment by LennyPenny** [comment]
exactly

**Comment by Tieske** [comment]
@LennyPenny can you test again with the tests currently available? just released 2.0, so if they all pass, I'll upload another rockspec with 5.3 support.

**Comment by saucisson** [comment]
It seems that there is still no rock for copas 2 and lua 5.3. Is there a compatibility problem?

**Comment by Tieske** [comment]
I just uploaded new rockspecs (for 2.0.0 and the cvs rockspec) adjusted to accept Lua 5.3 as target Lua version.
