### ISSUE TITLE
copas.connect() hangs forever if connecting to nonexistent host/port

### ISSUE THREAD

**Issue by nolar** [keplerproject/copas#31]
This code hangs forever if the remote side does not exist and does not accept any connections (i.e., nothing is listening on the port):

```
local socket = require'socket'
local copas = require'copas'

copas.addthread(function()

    sock = socket.tcp()
    sock:settimeout(10)

    print('go on...')

    local _,err = copas.connect(sock,"10.211.55.2","8080")

    print('done')
    print(err)
end)

copas.loop()
```

**Expected behavior:** fail with error immediately ("connection refused" is returned immediately under the hood) or at least after 10 seconds.

The reason is this line of code in copas.lua:

```
function copas.connect(skt, host, port)
  skt:settimeout(0)
  ...
```

It just resets the timeout on the socket. The reason and purpose of this call is unclear to me, so I cannot suggest a solution. Removing this line fixes the bug, though ("connection refused" error returned immediately).

PS: Windows 7, Lua 5.1.4

**Comment by nolar** [comment]
PPS: Though, removing settiteout(0) would make it blocking. The actual reason is that the error returned is "timeout" instead of "connection refused" (can be seen by adding debug prints in copas.connect()). 

Even when the server is started and begins to listen on the specified host & port, the connection does never occur, and the sample script stays frozen forever.

**Comment by Tieske** [comment]
I have to look into it, but it has similarities with #21, which also had an issue due to a bad error message from LuaSocket. Imho LuaSocket should return "connection refused" and not "timeout".

Overall Copas lacks proper timeout management (requires its own timers on top of LuaSocket, as all LuaSocket calls should be non-blocking). So maybe it's time to implement those. That would be a workaround for this issue at least.

PS. what LuaSocket version did you use? have you tried and older version?

**Comment by nolar** [comment]
Ah, right. Here:

```
C:\>luarocks --version
luarocks 2.0.2
LuaRocks main command-line interface

C:\>luarocks list

Installed rocks:
----------------

copas
   2.0.0-1 (installed) - C:\Program Files (x86)\Lua\5.1\rocks

coxpcall
   1.15.0-1 (installed) - C:\Program Files (x86)\Lua\5.1\rocks

lua-websockets
   v2.1-1 (installed) - C:\Program Files (x86)\Lua\5.1\rocks

luabitop
   1.0.2-1 (installed) - C:\Program Files (x86)\Lua\5.1\rocks

luafilesystem
   1.5.0-1 (installed) - C:\Program Files (x86)\Lua\5.1\rocks

luasocket
   3.0rc1-2 (installed) - C:\Program Files (x86)\Lua\5.1\rocks

luazip
   1.2.3-2 (installed) - C:\Program Files (x86)\Lua\5.1\rocks

md5
   1.1.2-1 (installed) - C:\Program Files (x86)\Lua\5.1\rocks

struct
   1.4-1 (installed) - C:\Program Files (x86)\Lua\5.1\rocks
```

Everything was installed automatically as dependencies for ```luarocks install lua-websockets``` (including copas). I did not install this packages directly.

**Comment by nolar** [comment]
No, I did not try the older version. I could try it in the next few days. Which version should I try (I am not a Lua developer, so I don't know the ecosystem well)?

**Comment by Tieske** [comment]
try the LuaSocket 2.x version, something like

`luarocks remove luasocket --force`

followed by 

`luarocks install luasocket-2.0.2-5`

Didn't test, so might need some tweaks

**Comment by Tieske** [comment]
with the new timeouts (in `master`) this now works for me;

```lua
local socket = require'socket'
local copas = require'copas'

copas.addthread(function()

    local sock = copas.wrap(socket.tcp())   --> note: wrap the socket into a copas one
    sock:settimeout(10)

    print('go on...')

    local _,err = sock:connect("10.211.55.2","8080")  --> connect on the "sock" object, not copas.connect

    print('done')
    print(err)
end)

copas.loop()
```

it gives me (after 10 seconds);
```
$ lua tests/issue31.lua
go on...
done
timeout
$
```

**Comment by Tieske** [comment]
without using Copas;
```lua

local sock = socket.tcp()
sock:settimeout(10)

print('go on...')

local _,err = sock:connect("10.211.55.2","8080")

print('done')
print(err)
```
I get the exact same result.

So now seems to work as expected.
closing this
