### ISSUE TITLE
A different kind of timeout

### ISSUE THREAD

**Issue by GReagle** [keplerproject/copas#33]
First of all, thanks for the great library.

Copas has a timeout functionality already in step() and loop() and it works fine.  This timeout applies to waiting for a new connection.

I wonder if it would be possible to implement a different kind of timeout: a timeout for an already open connection so that a client cannot keep it open forever.

Does that make sense?  See http://libmill.org/tutorial.html#step5.

**Comment by Tieske** [comment]
Indeed it is. It's on my to do list to implement the LuaSocket timeouts, but then in a non-blocking Copas way.
