### ISSUE TITLE
Revise errorhandlers

### ISSUE THREAD

**Issue by Tieske** [keplerproject/copas#39]
The errorhandlers are called after the coroutine returns, this means that they will not have a stacktrace, which makes it very cumbersome to track down errors in handlers/coroutines.

Revising them by wrapping the handler function in an `xpcall` which attaches the stacktrace to the error before reporting.

**Comment by mpeterv** [comment]
It's also possible to call debug.traceback on failed coroutine directly, the trace will start at error.

**Comment by Tieske** [comment]
yes, that is probably a better solution, less overhead. thx for bringing it to my attention!

**Comment by pranas** [comment]
Hey, I was looking for a way to get better crash reporting (stack traces) with copas and stumbled upon this thread. Is this going to be ever resolved? Any workaround you can suggest in the mean time?

**Comment by mpeterv** [comment]
@pranas There is `copas.setErrorHandler` function that sets error handler to be called after anerror in current thread. Default handler prints the error, associated socket and coroutine. You can set it to also print traceback, like this (do this in every callback thread):

```lua
copas.setErrorHandler(function(msg, co, skt)
   print(msg, co, skt)
   print(debug.traceback(co))
end)
```

Currently it's not possible to rethrow the error as errors inside error handler are ignored.

**Comment by pranas** [comment]
@mpeterv awesome, thanks! 👍

**Comment by pranas** [comment]
@mpeterv having stack traces are great! However we see that error message sometimes comes in as nil. We checked and the same issue applies when you use default error handler. Are you aware of this problem? Any workaround for it?

**Comment by pranas** [comment]
We tested stack traces by triggering crash with ``undefinedFunction()`` and error message was nil.

**Comment by mpeterv** [comment]
Can't reproduce using this test case:

```lua
local copas = require "copas"

copas.addthread(function()
   copas.setErrorHandler(function(msg, co)
      print(msg)
      print(debug.traceback(co))
   end)

   undefinedFunction()
end)
```

Output:

```
testerror.lua:9: attempt to call global 'undefinedFunction' (a nil value)
stack traceback:
	testerror.lua:9: in function <testerror.lua:3>
	(tail call): ?
```

**Comment by pranas** [comment]
Ok, maybe an error on my side, can't reproduce it.
