### ISSUE TITLE
Copas wrapper bugs?

### ISSUE THREAD

**Issue by robzed** [keplerproject/copas#41]
In the copas.lua ... copas socket wrapper... I think these two are wrong:

                   setoption = function(self, ...) return self.setoption:accept(...) end,
                   shutdown = function(self, ...) return self.shutdown:accept(...) end,

Shouldn't they be: 

                   setoption = function(self, ...) return self.socket:setoption(...) end,
                   shutdown = function(self, ...) return self.socket:shutdown(...) end,

**Comment by Tieske** [comment]
Good catch! thanks for reporting
