### ISSUE TITLE
Make running tests easier

### ISSUE THREAD

**Issue by mpeterv** [keplerproject/copas#47]
I'd like to be able to just run `make test` (or some other single command) to execute all tests. That'll make testing easier, both manual and automatic (running tests on travis-ci would be nice).

- [x] Ensure that failing tests exit with non-zero instead of just printing an error message
- [x] Ensure that tests can be run from root project directory
- [x] Ensure that tests use local copas sources
- [x] \(optional\) Move supporting .pem files into a subdirectory
- [x] Make `largetransfer` test run faster than 2 minutes
- [x] Add `test` target to Makefile or some other way to run all tests
- [ ] Ensure that tests exercise all `copas.*` modules
- [x] Add a separate target for running tests with coverage

**Comment by hishamhm** [comment]
I tweaked the `largetransfer` test accordingly, since I had my hands in it

**Comment by mpeterv** [comment]
@hishamhm that tweak is on `copas_sleep` branch, not on master =(

**Comment by Tieske** [comment]
I think some test scripts I wrote aren't even proper tests, but more demo like scripts. Would need to revisit that.

An would love to have Travis on this. Been holding it of because busted still has no async support in version 2-RCs.

**Comment by mpeterv** [comment]
@Tieske I tried to use luassert at least but it doesn't work well as copas likes to eat errors inside threads. Well, it prints them, but doesn't propagate.

**Comment by hishamhm** [comment]
@mpeterv Oops! Cherry-picked!

**Comment by hishamhm** [comment]
What if we just start running on Travis some of the tests/demos we have? That would be a start. I'm tweaking a branch to try this.

**Comment by hishamhm** [comment]
weeee https://travis-ci.org/keplerproject/copas/builds/116173518

**Comment by hishamhm** [comment]
The current `make test` prepends `$PWD/src/?.lua` to the package.path, so I believe it ensures that tests use local copas sources.

**Comment by hishamhm** [comment]
I added a task there because right now coverage is artificially high due to the fact that only `copas` and `copas.http` are being exercised (and therefore computed).

**Comment by mpeterv** [comment]
Added a test for copas.limit. Some error checking patterns (ensuring that all threads complete and running a helper thread counting time or thread switches to handle timeouts) should be moved to a common module.

**Comment by mpeterv** [comment]
I've converted two smaller tests and coverage didn't increase. But it's something. I suggest that remaining files (`test.lua`, `testasyncspeed.lua` and `cosocket.lua`) are moved to `examples/` or removed. Not sure if `cosocket.lua` does anything useful.

**Comment by mpeterv** [comment]
Added a separate target for running tests with coverage. Covering remaining modules would be nice but is outside of original scope of this issue, so I'm closing this. @hishamhm @Tieske thanks!

**Comment by ildar** [comment]
@hishamhm ,
> I tweaked the largetransfer test accordingly, since I had my hands in it

I don't see it fixed. Can anyone confirm?

**Comment by hishamhm** [comment]
@ildar It's here: https://github.com/keplerproject/copas/commit/45d9b2321acabda8b1009c8f07d8f6d5e30f5820#diff-89fe0de6848172de5166277c3d0739fa
