### ISSUE TITLE
coxpcall dependency on LuaJIT

### ISSUE THREAD

**Issue by hishamhm** [keplerproject/copas#50]
Is coxpcall needed in LuaJIT? When running the tests in Travis, I forgot to add the coxpcall dependency and noticed that the tests passed in Lua 5.2, 5.3 and failed in 5.1 and LuaJIT.

Maybe the test can be made
```
if _VERSION == "Lua 5.1" and not jit then
```

**Comment by mpeterv** [comment]
It isn't be needed and recent version of coxpcall is a noop under LuaJIT already. But Luarocks should just always install it?

**Comment by Tieske** [comment]
install yes, use no. I think @hishamhm meant the usage by Copas, based on its version check. It only uses it for 5.1, which includes Luajit. And we should exclude Luajit.

**Comment by hishamhm** [comment]
@mpeterv LuaRocks always installs it, but that's a limitation/weakness of LuaRocks (to be fixed). Copas can be smarter than that.
