### ISSUE TITLE
copas.removeserver(skt) always closes skt

### ISSUE THREAD

**Issue by hishamhm** [keplerproject/copas#55]
I have a scenario where I need to occasionally check for a socket, so I add it with `addthread` when I need to and then I remove it with `removeserver` when I'm done, but I don't want to close and reopen the socket each time; I want to just leave it open (so that no-one else takes over the port number while the application runs).

I wrote this hack in my code (highly dependent on the Copas implementation) to stop it from closing:

``` lua
-- HACK to stop copas.removeserver(wskt) from calling wskt:close()                                                                   
local proxy = setmetatable({ socket = wskt, close = function() end }, getmetatable(copas.wrap(wskt)))                            
copas.removeserver(proxy)                                                                                                        
```

Would it be possible to add an extra flag argument to `copas.removeserver` to stop it from closing the socket automatically? I can send a PR if the idea is accepted.

**Comment by Tieske** [comment]
seems like a good idea. With a PR, can you include a doc update?

Thx!
