### ISSUE TITLE
Does LuaJIT require coxpcall ?

### ISSUE THREAD

**Issue by fperrad** [keplerproject/copas#63]
`coxpcall` is mandatory with PUC Lua 5.1.
But with LuaJIT, there is a mismatch between these 2 files:
http://github.com/keplerproject/copas/blob/master/src/copas.lua#L28-L30 --> not required
http://github.com/keplerproject/copas/blob/master/src/copas/limit.lua#L13-L15 --> required

**Comment by mpeterv** [comment]
Coxpcall is not required under LuaJIT, the line in limit.lua can be fixed. Although latest version of coxpcall is clever enough to return standard (x)pcall instead of co(x)pcall when using LuaJIT.

**Comment by Tieske** [comment]
PR #64 was merged.
