### ISSUE TITLE
Update Luarock

### ISSUE THREAD

**Issue by CodelessFuture** [keplerproject/copas#66]
Can I ask you to update the luarockt for this project, please?

**Comment by Tieske** [comment]
@CodelessFuture Why? there is nothing to release (a very minor cleanup only) or am I missing something?

**Comment by CodelessFuture** [comment]
I need all the upgrade that let me use Xavante with Lua 5.3. I successfully launch Sailor only after applying all the last patch on master branch of copas, xavante, wsapi and so on....

**Comment by Tieske** [comment]
But the current rockspec already supports 5.3? see https://github.com/keplerproject/copas/blob/master/rockspec/copas-2.0.2-1.rockspec#L22

**Comment by CodelessFuture** [comment]
I only know that for let Sailor work with Lua 5.3 I have to manually apply the master repo source on Xavante, wsapi, copas and so on.........if you don't want to update the rock with your help I can analyze the errors I receive with the keplerproject rocks

**Comment by Tieske** [comment]
I don't know what errors you get? But if you take Lua 5.3, then Copas by it self would install properly no?

Maybe there is an issue with the dependency chain? one of the other packages requiring an older version of Copas, which then does not have 5.3 listed in its rockspec?

**Comment by CodelessFuture** [comment]
I'm sorry. You are right! The only rocks need to be updated for letting Sailor! works with Lua 5.3 are cgilua, coxpcall and wsapi
