### ISSUE TITLE
copas.loop() never stop

### ISSUE THREAD

**Issue by loustak** [keplerproject/copas#67]
Hello, 
the cpas.loop() function never stop. Here is the whole code:
```
local socket = require("socket")
local copas = require("copas")

local host = "127.0.0.1"
local port = 9982
local server, err = socket.bind(host, port)

function connectionHandler(socket)
  while true do
    local data, err = copas.receive(socket)
    if data == nil then
      print("Client socket: " .. err)
      break
    else
      print("Message: " .. data)
    end
  end
  print("Client disconnected")
end

function errorHandler(error, coroutine, socket)
  print("Error handler: " .. error)
end

copas.autoclose = true
copas.addserver(server, connectionHandler)
copas.setErrorHandler(errorHandler)

print("Server started")
copas.loop()
print("Server stopped")
```

In this code everything works, but when a client disconnect from the server, the connectionHandler break the loop and then display the "Client disconnected" message but the server still run, the "Server stopped" message is never displayed. Why?

Thanks for help.

**Comment by mpeterv** [comment]
Server thread does not stop after handling a single client, it will continue accepting new connections and handling other existing ones.
