### ISSUE TITLE
Version format for git tags.

### ISSUE THREAD

**Issue by neheb** [keplerproject/copas#70]
Is it possible to switch to Xx.Yy.Zz format? I ask as I've been asked to do this for OpenWrt where most versions of packages follow that format. Changing it upstream would simplify the process.

**Comment by Tieske** [comment]
Personally I don't have a preference, except to remain consistent. I have no idea who elses projects we'd be breaking if we'd change the format. So not likely this is getting changed. Sorry.

**Comment by Tieske** [comment]
btw: where is OpenWRT using Copas? I wasn't aware of it

**Comment by neheb** [comment]
This was the original discussion: https://github.com/openwrt/packages/pull/7497

**Comment by Tieske** [comment]
just thinking out loud, I don't think there are any adverse effects if we tag using two formats? as long as they point to the same commit

**Comment by Tieske** [comment]
ok, tags added for the 2.0.x series

**Comment by neheb** [comment]
Great. OpenWrt pull request should be fine now.
