### ISSUE TITLE
Is there an option to set a callback?

### ISSUE THREAD

**Issue by otgo** [keplerproject/copas#76]
Ex. I have my client on Lua using copas:

###### client.lua
```lua
-- code using copas.addserver()
```

###### Myscript.lua
```lua
-- here im using my server
-- connection here, here im using send
x:send("string") -- i want, if my server returns something, i get it here, how?

```

**Comment by Tieske** [comment]
You could do that, but that would be an ugly piece of code. Copas was designed to work with coroutines which are far more elegant. Check the documentation it has some example.

**Comment by otgo** [comment]
okay, thanks anyway! :)
