### ISSUE TITLE
Support SNI for HTTPS

### ISSUE THREAD

**Issue by amyspark** [keplerproject/copas#77]
Hey,

Copas currently doesn't support HTTPS servers that need SNI support. This breaks websites behind Cloudflare or shared hosting services.

LuaSec already has support for it, so it would be a matter of adding the relevant lines to `dohandshake`.

**Comment by Tieske** [comment]
@amyspark any hints/links on how to reproduce this? and how to fix it?

**Comment by amyspark** [comment]
@Tieske I've just sent in the patch I have here.
